version: '3'
services:
  db:
    image: mysql
    container_name: loginup.mysql
    environment:
      MYSQL_DATABASE: 'loginup'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:mysql://db -schemas=loginup -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db