#aluraTest:
#  secrect: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
## App Properties
app:
  jwtSecret: JWTSuperSecretKey
  expiration: 604800000

# Spring Boot configuration
spring:
  profiles:
    active: development
  # Database
  datasource:
    url: 'jdbc:mysql://localhost:15432/quizzes?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true'
    username: 'admin'
    password: 'admin'
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: false
    generate-ddl: false